### ISSUE TITLE
Send command states CR not LF

### ISSUE THREAD

**Issue by EventReplay** [bitfocus/companion-module-kramer-vp734#1]
@JeffreyDavidsz being nosey again and looking over code, looks great to me.
My only comment is manual states CR \r not LF \n don't know if it will make a difference.
Sorry don't have access to this model so can't test myself but hopefully @dgsauer can give some feedback.

**Comment by JeffreyDavidsz** [comment]
No problem, the thing is that a comparison model that was already in the list accepts LF. There is also a # in front of the commands according to the manual. I'm hoping that Kramer keeps there protocols the same, otherwise its a easy fix

**Comment by EventReplay** [comment]
I didn't see any reference to a # in the the two different 734 manuals I've seen, so I don't think that will be an issue.
I've dealt with a few kramer models for Crestron Programs, They have a Protocol 2000, a Protocol 3000 and the protocol that this model uses! So at least 3 Protocols not all the same unfortunaly.
@SteveTherrien uses a \r in his Kramer Matrix module for 2000/3000 Protocol, so I would say if there are any issues it will probably be that, and as you say an easy fix.
Regards

Nigel

**Comment by JeffreyDavidsz** [comment]
@dgsauer did you got any chance to test?

**Comment by dgsauer** [comment]
Having trouble installing the module.  Can you point me to the instructions
for doing so?

**Comment by EventReplay** [comment]
@dgsauer you just need to download and use the lastest v2 build from:
https://builds.bitfocus.io/companion/

**Comment by dgsauer** [comment]
Oh, I was looking for a new 1.4 build.  Thanks!

**Comment by dgsauer** [comment]
BTW, I was able to test the module you created for the Kramer VP-734.
Everything I've tried so far worked great.  Thank you very much for your
help!

**Comment by JeffreyDavidsz** [comment]
Thanks for testing!
